apiVersion: v1
kind: Namespace
metadata:
  name: sro
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: sro-qa
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    istio-injection: enabled
