apiVersion: v1
kind: Namespace
metadata:
  name: sro
  # labels:
  #   istio-injection:
  #     enabled
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sro-qa
#   # labels:
#   #   istio-injection:
#   #     enabled
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sro-dev
#   # labels:
#   #   istio-injection:
#   #     enabled