apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: sro
  labels:
    app: accounts
    version: v1
    sro: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
      version: v1
  template:
    metadata:
      labels:
        app: accounts
        version: v1
        sro: microservice
    spec:
      containers:
        - name: accounts
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/accounts:0.0.1
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: sro-config
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: jwt-certs
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: sro-config
          secret:
            secretName: sro-config 
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: sro
  labels:
    app: accounts
    service: accounts
spec:
  type: ClusterIP
  selector:
    app: accounts
    version: v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-headless
  namespace: sro
  labels:
    app: accounts
    headless: accounts
spec:
  clusterIP: None
  selector:
    app: accounts
    version: v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP