apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: sro
  labels:
    app: accounts
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
      version: v1
  template:
    metadata:
      labels:
        app: accounts
        version: v1
    spec:
      containers:
        - name: accounts
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/accounts:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SRO_ACCOUNTS_MODE
              value: "release"
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: sro-db
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: jwt-certs
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: sro-db
          secret:
            secretName: accounts-database
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: sro
  labels:
    app: accounts
    service: accounts
spec:
  type: ClusterIP
  selector:
    app: accounts
    version: v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: accounts-database
  namespace: sro
data:
  db.yaml: '{{DATABASE_FILE}}'