apiVersion: apps/v1
kind: Deployment
metadata:
  name: characters
  namespace: sro
  labels:
    app: characters
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: characters
      version: v1
  template:
    metadata:
      labels:
        app: characters
        version: v1
    spec:
      containers:
        - name: characters
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/characters:latest
          ports:
          - containerPort: 8081
          imagePullPolicy: Always
          env:
            - name: SRO_ACCOUNTS_HOST 
              value: "accounts"
            - name: SRO_ACCOUNTS_PORT
              value: "80"
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: sro-db
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: jwt-certs
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: sro-db
          secret:
            secretName: characters-database
---
apiVersion: v1
kind: Service
metadata:
  name: characters
  namespace: sro
  labels:
    app: characters
    service: characters
spec:
  type: ClusterIP
  selector:
    app: characters
    version: v1
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP 
      name: http-web
---
apiVersion: v1
kind: Secret
metadata:
  name: characters-database
  namespace: sro
data:
  db.yaml: '{{DATABASE_FILE}}'