apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: sro
  labels:
    app: chat
    version: v1
    sro: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
      version: v1
  template:
    metadata:
      labels:
        app: chat
        version: v1
        sro: microservice
    spec:
      containers:
        - name: chat
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/chat:0.0.1
          ports:
          - containerPort: 8081
          imagePullPolicy: Always
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: sro-config
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: jwt-certs
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: sro-config
          secret:
            secretName: sro-config 
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: sro
  labels:
    app: chat
    service: chat
    api: http
spec:
  type: ClusterIP
  selector:
    app: chat
    version: v1
  ports:
    - port: 80
      targetPort: 8180
      protocol: TCP
      appProtocol: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: chat-grpc
  namespace: sro
  labels:
    app: chat
    service: chat
    api: grpc
spec:
  type: LoadBalancer
  selector:
    app: chat
    version: v1
  ports:
    - port: 8180
      targetPort: 8180
      protocol: TCP
      appProtocol: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: chat-headless
  namespace: sro
  labels:
    app: chat
    headless: chat
spec:
  clusterIP: None
  selector:
    app: chat
    version: v1
  ports:
    - port: 80
      targetPort: 8180
      protocol: TCP
      appProtocol: grpc