apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sro
  labels:
    app: frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sro
  labels:
    app: frontend
    service: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    version: v1
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http