apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-proxy
  namespace: sro
  labels:
    app: oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth-proxy"
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      containers:
      - name: oauth-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.4.0"
        ports:
        - containerPort: 4180
        args:
          - --upstream=static://200
          - --set-xauthrequest=true
          - --pass-host-header=true
          - --pass-access-token=true
          - --whitelist-domain=.shatteredrealmsonline.com
          - --scope="openid profile roles'
          - --set-authorization-header=true
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --skip-provider-button=true
          - --skip-jwt-bearer-tokens=true
          - --request-logging=true
          - --auth-logging=true
          - --standard-logging=true
        env:
          # OIDC Config
          - name: "OAUTH2_PROXY_PROVIDER"
            value: "keycloak-oidc"
          - name: "OAUTH2_PROXY_OIDC_ISSUER_URL"
            value: "https://sso.shatteredrealmsonline.com/realms/default"
          - name: "OAUTH2_PROXY_CLIENT_ID"
            value: "oauth2-proxy"
          - name: "OAUTH2_PROXY_CLIENT_SECRET"
            value: "<SECRET>"
          # Cookie Config
          - name: "OAUTH2_PROXY_COOKIE_SECURE"
            value: "true"
          - name: "OAUTH2_PROXY_COOKIE_SECRET"
            value: "<SECRET>"
          - name: "OAUTH2_PROXY_COOKIE_DOMAINS"
            value: "api.shatteredrealmsonline.com,shatteredrealmsonline.com"
          # Proxy config
          - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
            value: "*"
          - name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
            value: "*"
          - name: "OAUTH2_PROXY_HTTP_ADDRESS"
            value: "0.0.0.0:4180"
          - name: "OAUTH2_PROXY_SET_XAUTHREQUEST"
            value: "true"
          - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
            value: "true"
          - name: OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY
            value: "true"
          - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
            value: "true"
          - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: oauth-proxy
  namespace: sro
  labels:
    app: oauth-proxy
spec:
  type: NodePort
  selector:
    app: oauth-proxy
  ports:
  - name: http-oauthproxy
    port: 4180
    nodePort: 31023
