apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: accounts
  namespace: sro
spec:
  hosts:
  - "api.shatteredrealmsonline.com"
  - "api.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
  - match:
    - uri:
        prefix: /accounts/
    - uri:
        exact: /accounts
    rewrite:
      uri: '/'
    route:
    - destination:
        host: accounts
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: accounts
  namespace: sro-qa
spec:
  hosts:
  - "qa.api.shatteredrealmsonline.com"
  - "qa.api.shatteredrealms.online"
  gateways:
  - istio-system/sro-qa-gateway
  http:
  - match:
    - uri:
        prefix: /accounts/
    - uri:
        exact: /accounts
    rewrite:
      uri: '/'
    route:
    - destination:
        host: accounts
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: accounts
  namespace: sro-dev
spec:
  hosts:
  - "dev.api.shatteredrealmsonline.com"
  - "dev.api.shatteredrealms.online"
  gateways:
  - istio-system/sro-dev-gateway
  http:
  - match:
    - uri:
        prefix: /accounts/
    - uri:
        exact: /accounts
    rewrite:
      uri: '/'
    route:
    - destination:
        host: accounts
        port:
          number: 80
      weight: 100