apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sro-api
  namespace: istio-system
spec:
  hosts:
  - "api.shatteredrealmsonline.com"
  - "api.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
########
# Chat #
########
  - match:
    - uri:
        prefix: /chat/
    - uri:
        exact: /chat
    rewrite:
      uri: '/'
    route:
    - destination:
        host: chat.sro.svc.cluster.local
        port:
          number: 80
      weight: 100
    corsPolicy: &cors
      allowOrigins:
        - regex: ".*"
        - regex: "^.*$"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
        - grpc-timeout
        - authorization
      maxAge: 1728s
      exposeHeaders:
        - grpc-status
        - grpc-message
  - route:
    - destination:
        host: chat-grpc.sro.svc.cluster.local
        port:
          number: 8180
    match:
      - port: 8180
    corsPolicy: *cors
##############
# Characters #
##############
  - match:
    - uri:
        prefix: /characters/
    - uri:
        exact: /characters
    rewrite:
      uri: '/'
    route:
    - destination:
        host: character.sro.svc.cluster.local
        port:
          number: 80
      weight: 100
    corsPolicy: *cors
###############
# Gamebackend #
###############
  - match:
    - uri:
        prefix: /gamebackend/
    - uri:
        exact: /gamebackend
    rewrite:
      uri: '/'
    route:
    - destination:
        host: gamebackend.sro.svc.cluster.local
        port:
          number: 80
      weight: 100
    corsPolicy: *cors
