apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  namespace: istio-system
spec:
  hosts:
  - "shatteredrealmsonline.com"
  - "shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
    - route:
        - destination:
            host: frontend.sro.svc.cluster.local
            port:
              number: 80
          weight: 100
      match:
        - uri:
            prefix: /