apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gamebackend
  namespace: sro
spec:
  hosts:
  - "api.shatteredrealmsonline.com"
  - "api.shatteredrealms.online"
  gateways:
  - sro-gateway
  http:
  - match:
    - uri:
        prefix: /gamebackend/
    - uri:
        exact: /gamebackend
    rewrite:
      uri: '/'
    route:
    - destination:
        host: gamebackend
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gamebackend
  namespace: sro-qa
spec:
  hosts:
  - "qa.api.shatteredrealmsonline.com"
  - "qa.api.shatteredrealms.online"
  gateways:
  - sro-qa-gateway
  http:
  - match:
    - uri:
        prefix: /gamebackend/
    - uri:
        exact: /gamebackend
    rewrite:
      uri: '/'
    route:
    - destination:
        host: gamebackend
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gamebackend
  namespace: sro-dev
spec:
  hosts:
  - "dev.api.shatteredrealmsonline.com"
  - "dev.api.shatteredrealms.online"
  gateways:
  - sro-dev-gateway
  http:
  - match:
    - uri:
        prefix: /gamebackend/
    - uri:
        exact: /gamebackend
    rewrite:
      uri: '/'
    route:
    - destination:
        host: gamebackend
        port:
          number: 80
      weight: 100