apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sro-grpc-api
  namespace: istio-system
spec:
  hosts:
  - "*.grpc.api.shatteredrealmsonline.com"
  - "*.grpc.api.shatteredrealms.online"
  - "grpc.api.shatteredrealmsonline.com"
  - "grpc.api.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
########
# Chat #
########
  - route:
    - destination:
        host: chat.sro.svc.cluster.local
        port:
          number: 80
    match:
      - port: 8180
    corsPolicy:
      allowOrigin:
        - "*"
        - ".*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
        - grpc-timeout
        - authorization
      maxAge: 1728s
      exposeHeaders:
        - grpc-status
        - grpc-message
  - route:
    - destination:
        host: gamebackend.sro.svc.cluster.local
        port:
          number: 80
    match:
      - port: 8082
    corsPolicy:
      allowOrigin:
        - "*"
        - ".*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
        - grpc-timeout
        - authorization
      maxAge: 1728s
      exposeHeaders:
        - grpc-status
<<<<<<< HEAD
        - grpc-message
=======
        - grpc-message
>>>>>>> 1a2bcde8027684eae11c830616d220d6b991d575
