apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
  - "kiali.shatteredrealmsonline.com"
  - "kiali.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
  - match:
      - port: 443
    route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
      weight: 100
