apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sro-kibana
  namespace: istio-system
spec:
  hosts:
  - "kibana.shatteredrealmsonline.com"
  - "kibana.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: production-kb-http.logging.svc.cluster.local
        port:
          number: 5601
      weight: 100
