apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pgpool
  namespace: sro
spec:
  hosts:
  - pgpool-svc
  gateways:
  - istio-system/sro-gateway
  tcp:
  - match:
    - port: 5432
    route:
      - destination:
          host: accounts
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pgpool
  namespace: sro-qa
spec:
  hosts:
  - pgpool-svc
  gateways:
  - istio-system/sro-qa-gateway
  tcp:
  - match:
    - port: 5432
    route:
      - destination:
          host: accounts
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pgpool
  namespace: sro-dev
spec:
  hosts:
  - pgpool-svc
  gateways:
  - istio-system/sro-dev-gateway
  tcp:
  - match:
    - port: 5432
    route:
      - destination:
          host: accounts