apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sro-sso
  namespace: istio-system
spec:
  hosts:
  - "sso.shatteredrealmsonline.com"
  - "sso.shatteredrealms.online"
  - "admin.sso.shatteredrealmsonline.com"
  - "admin.sso.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
  - match:
    - uri:
        prefix: /
    # - uri:
    #     prefix: /realms/
    # - uri:
    #     prefix: /resources/
    # - uri:
    #     prefix: /admin/
    # - uri:
    #     exact: /robots.txt
    route:
    - destination:
        host: keycloak-service.auth.svc.cluster.local
        port:
          number: 8080
      weight: 100
