apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sro-sso
  namespace: istio-system
spec:
  hosts:
  - "sso.shatteredrealmsonline.com"
  - "sso.shatteredrealms.online"
  - "admin.sso.shatteredrealmsonline.com"
  - "admin.sso.shatteredrealms.online"
  gateways:
  - istio-system/sro-gateway
  http:
  - match:
    - uri:
        prefix: /js/
    - uri:
        prefix: /realms/
    - uri:
        prefix: /resources/
    - uri:
        prefix: /admin/
    - uri:
        exact: /robots.txt
    route:
    - destination:
        host: keycloak.sro.svc.cluster.local
        port:
          number: 80
      weight: 100