metrics:
  enabled: true
  resources:
    requests:
      cpu: .75
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1024Mi

witness:
  resources:
    requests:
      cpu: .75
      memory: 512Mi
    limits:
      cpu: 3
      memory: 1024Mi

pgpool:
  resources:
    requests:
      cpu: 1
      memory: 4096Mi
    limits:
      cpu: 4
      memory: 6144Mi

postgresql:
  resources:
    requests:
      cpu: 1
      memory: 4096Mi
    limits:
      cpu: 4
      memory: 6144Mi
