apiVersion: v1
kind: ConfigMap
metadata:
  name: sro-config
  namespace: sro
data:
  sro-character.yaml: |
    mode: 'prod'
    logLevel: 4
    postgres:
      host: 'postgres-postgresql-ha-pgpool'
    openTelemetryAddress: otel-collector-cluster-opentelemetry-collector.observability.svc.cluster.local:4317
    keycloak:
      baseURL: 'https://sso.shatteredrealmsonline.com'
    kafka:
      port: 9092
      host: 'my-cluster-kafka-bootstrap.kafka.svc'
    redis:
      master:
        host: redis-redis-cluster-0.redis-redis-cluster-headless.sro.svc.cluster.local
        port: 6379
      slaves:
        - host: redis-redis-cluster-1.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-2.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-3.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-4.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-5.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
  sro-chat.yaml: |
    mode: 'prod'
    logLevel: 4
    postgres:
      host: 'postgres-postgresql-ha-pgpool'
    openTelemetryAddress: otel-collector-cluster-opentelemetry-collector.observability.svc.cluster.local:4317
    keycloak:
      baseURL: 'https://sso.shatteredrealmsonline.com'
    kafka:
      port: 9092
      host: 'my-cluster-kafka-bootstrap.kafka.svc'
    redis:
      master:
        host: redis-redis-cluster-0.redis-redis-cluster-headless.sro.svc.cluster.local
        port: 6379
      slaves:
        - host: redis-redis-cluster-1.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-2.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-3.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-4.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-5.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
  sro-gameserver-service.yaml: |
    mode: 'prod'
    logLevel: 4
    postgres:
      host: 'postgres-postgresql-ha-pgpool'
    kafka:
      port: 9092
      host: 'my-cluster-kafka-bootstrap.kafka.svc'
    openTelemetryAddress: otel-collector-cluster-opentelemetry-collector.observability.svc.cluster.local:4317
    keycloak:
      baseURL: 'https://sso.shatteredrealmsonline.com'
    gsm:
      gameServerImage: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/game
    redis:
      master:
        host: redis-redis-cluster-0.redis-redis-cluster-headless.sro.svc.cluster.local
        port: 6379
      slaves:
        - host: redis-redis-cluster-1.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-2.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-3.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-4.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379
        - host: redis-redis-cluster-5.redis-redis-cluster-headless.sro.svc.cluster.local
          port: 6379

