apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: sro-dev
  labels:
    app: accounts
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
      version: v1
  template:
    metadata:
      labels:
        app: accounts
        version: v1
    spec:
      containers:
        - name: accounts
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/accounts/dev:latest
          imagePullPolicy: Always
          env:
            - name: PS_AUTH_JWT_PRIVATE_KEY_PATH
              value: "/etc/sro/auth/keys/key"
            - name: PS_AUTH_JWT_PUBLIC_KEY_PATH
              value: "/etc/sro/auth/keys/key.pub"
            - name: SRO_AUTH_MODE
              value: "release"
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: sro-db
              mountPath: "/etc/sro/"
              readOnly: true
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /v1/health
              port: 8080
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: jwt-certs
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: sro-db
          secret:
            secretName: database
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: sro-dev
  labels:
    app: accounts
    service: accounts
spec:
  type: ClusterIP
  selector:
    app: accounts
    version: v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: sro-dev
data:
  db.yaml: '{{DATABASE_FILE}}'