apiVersion: apps/v1
kind: Deployment
metadata:
  name: characters
  namespace: sro-dev
  labels:
    app: characters
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: characters
      version: v1
  template:
    metadata:
      labels:
        app: characters
        version: v1
    spec:
      containers:
        - name: characters
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/characters:0.0.1
          ports:
          - containerPort: 8081
          imagePullPolicy: Always
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: sro-config
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: jwt-certs
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: sro-config
          secret:
            secretName: sro-config 
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: characters
  namespace: sro-dev
  labels:
    app: characters
    service: characters
spec:
  type: ClusterIP
  selector:
    app: characters
    version: v1
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP