characters:
  remote:
    host: 'characters'
    port: 80
  mode: 'production'
  logLevel: 4
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: '{{CHARACTERS_DB_PASSWORD}}'
  keycloak:
    baseUrl: 'https://sso.shatteredrealmsonline.com'
    clientId: '{{KEYCLOAK_CHARACTERS_CLIENT_ID}}'
    clientSecret: '{{KEYCLOAK_CHARACTERS_CLIENT_SECRET}}'
gamebackend:
  remote:
    host: 'gamebackend'
    port: 80
  mode: 'production'
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: '{{GAMEBACKEND_DB_PASSWORD}}'
  keycloak:
    baseUrl: 'https://sso.shatteredrealmsonline.com'
    clientId: '{{KEYCLOAK_GAMEBACKEND_CLIENT_ID}}'
    clientSecret: '{{KEYCLOAK_GAMEBACKEND_CLIENT_SECRET}}'
chat:
  remote:
    host: 'chat'
    port: 80
  mode: 'production'
  kafka:
    port: 9092
    host: 'my-cluster-kafka-bootstrap'
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: '{{CHAT_DB_PASSWORD}}'
  keycloak:
    baseUrl: 'https://sso.shatteredrealmsonline.com'
    clientId: '{{KEYCLOAK_CHAT_CLIENT_ID}}'
    clientSecret: '{{KEYCLOAK_CHAT_CLIENT_SECRET}}'
agones:
  namespace: '{{NAMESPACE}}'
  allocator:
    remote:
      port: 443
      host: '{{AGONES_IP}}'
uptrace:
  host: 'sso.shatteredrealmsonline.com'
  port: 443
  id: '{{SRO_PROD_PROJ_ID}}'
  token: '{{SRO_PROD_PROJ_SECRET}}'
