character:
  remote:
    host: 'characters'
    port: 80
  mode: 'production'
  logLevel: 4
  postgres:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: '{{CHARACTERS_DB_PASSWORD}}'
  mongo:
    master:
      host: 'mongodb'
      username: 'root'
      password: '{{CHARACTERS_MONGO_PASSWORD}}'
  keycloak:
    id: '{{KEYCLOAK_CHARACTERS_CLIENT_ID}}'
    clientSecret: '{{KEYCLOAK_CHARACTERS_CLIENT_SECRET}}'
gamebackend:
  remote:
    host: 'gamebackend'
    port: 80
  mode: 'production'
  logLevel: 4
  postgres:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: '{{GAMEBACKEND_DB_PASSWORD}}'
  keycloak:
    id: '{{KEYCLOAK_GAMEBACKEND_CLIENT_ID}}'
    clientSecret: '{{KEYCLOAK_GAMEBACKEND_CLIENT_SECRET}}'
chat:
  remote:
    host: 'chat'
    port: 80
  mode: 'production'
  logLevel: 4
  kafka:
    port: 9092
    host: 'my-cluster-kafka-bootstrap'
  postgres:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: '{{CHAT_DB_PASSWORD}}'
  keycloak:
    id: '{{KEYCLOAK_CHAT_CLIENT_ID}}'
    clientSecret: '{{KEYCLOAK_CHAT_CLIENT_SECRET}}'
agones:
  namespace: '{{NAMESPACE}}'
  allocator:
    remote:
      port: 443
      host: '{{AGONES_IP}}'
keycloak:
  baseURL: 'https://sso.shatteredrealmsonline.com'
uptrace:
  host: 'sso.shatteredrealmsonline.com'
  port: 443
  id: '{{UPTRACE_PROJ_ID}}'
  token: '{{UPTRACE_PROJ_SECRET}}'
