accounts:
  remote:
    host: 'accounts'
    port: 80
  mode: 'production'
  logLevel: 4
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: 'KY1BjHKcki'
characters:
  remote:
    host: 'characters'
    port: 80
  mode: 'production'
  logLevel: 4
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: 'KY1BjHKcki'
gamebackend:
  remote:
    host: 'gamebackend'
    port: 80
  mode: 'production'
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: 'KY1BjHKcki'
chat:
  remote:
    host: 'chat'
    port: 80
  mode: 'production'
  kafka:
    port: 9092
    host: 'my-cluster-kafka-bootstrap'
  db:
    master:
      host: 'postgres-postgresql-ha-pgpool'
      password: 'KY1BjHKcki'
agones:
  namespace: 'sro'
  allocator:
    remote:
      port: 443
      host: '75.61.95.171'
uptrace:
  host: 'uptrace.dev'
  port: 443
  id: '1039'
  token: 'tS31BUtKNJgFvI29I8WGQA'
keycloak:
  baseUrl: https