apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: status-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}, {"HTTP": 8080}, {"HTTP": 8081}, {"HTTP": 8082}, {"HTTP": 8180}]'
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balanacer-name: sro-external-ingress
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "{{SRO_ARN}}"
  name: sro-external-ingress
  namespace: istio-system
  labels:
    app: sro-external-ingress
spec:
  ingressClassName: alb
  rules:
  - http: &https
      paths: 
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 443
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 8081
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 8082
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 8083
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 8180
        path: /
        pathType: Prefix
      - backend:
          service:
            name: istio-ingressgateway
            port: 
              number: 15021
        path: /healthz/ready
        pathType: Prefix
  # - host: "shatteredrealmsonline.com"
  #   http: &https
  #     paths: 
  #     - backend:
  #         service:
  #           name: istio-ingressgateway
  #           port: 
  #             number: 443
  #       path: /
  #       pathType: Prefix
  # - host: "*.shatteredrealmsonline.com"
  #   http: &https
  # - host: "shatteredrealmsonline.com"
  #   http: &https
  # - host: "*.shatteredrealms.online"
  #   http: &https
  # - host: "shatteredrealms.online"
  #   http: &https
