apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gateway-grpc-web-filter
  namespace: sro
spec:
  workloadSelector:
    labels:
      sro: microservice
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: ANY
      # listener:
      #   filterChain:
      #     filter:
      #       name: "envoy.filters.network.http_connection_manager"
      #       subFilter:
      #         name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.grpc_web
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb          
  # - applyTo: CLUSTER
  #   match:
  #     context: SIDECAR_OUTBOUND
  #   patch:
  #     operation: MERGE
  #     value:
  #       http2_protocol_options:
  #         max_concurrent_streams: 47707
  # - applyTo: CLUSTER
  #   match:
  #     context: SIDECAR_OUTBOUND
  #   patch:
  #     operation: MERGE
  #     value:
  #       typed_extension_protocol_options:
  #         envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
  #           '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
  #           common_http_protocol_options:
  #             idle_timeout: 4s
  #           use_downstream_protocol_config: 
  #             http2_protocol_options: {}
  #             http_protocol_options: {}
  # - applyTo: CLUSTER
  #   match:
  #     context: SIDECAR_INBOUND
  #   patch:
  #     operation: MERGE
  #     value:
  #       typed_extension_protocol_options:
  #         envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
  #           '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
  #           common_http_protocol_options:
  #             idle_timeout: 4s
  #           use_downstream_protocol_config: 
  #             http2_protocol_options: {}
  #             http_protocol_options: {}