apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sro-gateway
  namespace: sro
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https-443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "istio-tls-secret"
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sro-qa-gateway
  namespace: sro-qa
spec:
  selector:
    istio: ingressgateway-qa
  servers:
    - port:
        number: 443
        name: https-443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "istio-qa-tls-secret"
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sro-dev-gateway
  namespace: sro-dev
spec:
  selector:
    istio: ingressgateway-dev
  servers:
    - port:
        number: 443
        name: https-443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "istio-dev-tls-secret"
      hosts:
        - "*"