apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: sro-istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: "oauth2-proxy"
      envoyExtAuthzHttp:
        service: "oauth-proxy.sro.svc.cluster.local"
        port: "4180"
        includeHeadersInCheck: 
          - "authorization"
          - "cookie"
          - "x-forwarded-access-token"
          - "x-forwarded-user"
          - "x-forwarded-email"
          - "x-forwarded-proto"
          - "proxy-authorization"
          - "user-agent"
          - "x-forwarded-host"
          - "from"
          - "x-forwarded-for"
          - "accept"
          - "x-auth-request-redirect"
        headersToUpstreamOnAllow: 
          - "authorization"
          - "path"
          - "x-auth-request-user"
          - "x-auth-request-email"
          - "x-auth-request-access-token"
          - "x-forwarded-access-token"
          - "cookie"
        headersToDownstreamOnDeny: 
          - "content-type"
          - "set-cookie"
        includeAdditionalHeadersInCheck:
          X-Auth-Request-Redirect: '%REQ(x-forwarded-proto)%://%REQ(:authority)%%REQ(:path)%'
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
                protocol: TCP
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
              - port: 15012
                targetPort: 15012
                name: tcp-istiod
                protocol: TCP
              - port: 15443
                targetPort: 15443
                name: tls
                protocol: TCP
              - port: 8180
                targetPort: 8180
                name: i-grpc-8180
                protocol: TCP
              - port: 8081
                targetPort: 8081
                name: i-grpc-8081
                protocol: TCP
              - port: 8082
                targetPort: 8082
                name: i-grpc-8082
                protocol: TCP

      # - name: istio-ingressgateway-qa
      #   namespace: istio-system
      #   enabled: true
      #   label:
      #     istio: ingressgateway-qa

      # - name: istio-ingressgateway-dev
      #   namespace: 
      #   enabled: true
      #   label:
      #     istio: ingressgateway-dev