apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: sro-istiocontrolplane
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
                protocol: TCP
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
              - port: 15012
                targetPort: 15012
                name: tcp-istiod
                protocol: TCP
              - port: 15443
                targetPort: 15443
                name: tls
                protocol: TCP
              - port: 8180
                targetPort: 8180
                name: i-grpc-8180
                protocol: TCP

      # - name: istio-ingressgateway-qa
      #   namespace: istio-system
      #   enabled: true
      #   label:
      #     istio: ingressgateway-qa

      # - name: istio-ingressgateway-dev
      #   namespace: 
      #   enabled: true
      #   label:
      #     istio: ingressgateway-dev