apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: shatteredrealmsonline.com
  dnsNames:
  - shatteredrealmsonline.com
  - api.shatteredrealmsonline.com
  - sso.shatteredrealmsonline.com
  - "*.sso.shatteredrealmsonline.com"
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
