apiVersion: v1
kind: Service
metadata:
  name: public-postgresql
spec:
  selector:
    app.kubernetes.io/name: postgresql-ha
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer