apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: sro
  labels:
    app: chat
    version: v1
    sro: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
      version: v1
  template:
    metadata:
      labels:
        app: chat
        version: v1
        sro: microservice
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      containers:
        - name: chat
          image: 779965382548.dkr.ecr.us-east-1.amazonaws.com/sro/chat-service:0.5.2
          ports:
          - containerPort: 8180
          imagePullPolicy: Always
          volumeMounts:
            - name: sro-config
              mountPath: "/etc/sro/"
              readOnly: true
          env:
            - name: SRO_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql-ha-postgresql
                  key: password
            - name: SRO_KEYCLOAK_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-chat
                  key: id
            - name: SRO_KEYCLOAK_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-chat
                  key: secret
            - name: SRO_REDIS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-redis-cluster
                  key: redis-password
            - name: SRO_SERVER_HOST
              value: 0.0.0.0
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: sro-config
          configMap:
            name: sro-config 
            items:
              - key: sro-chat.yaml
                path: sro-chat.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: sro
  labels:
    app: chat
    service: chat
    api: http
spec:
  type: ClusterIP
  selector:
    app: chat
    version: v1
  ports:
    - port: 80
      targetPort: 8180
      protocol: TCP
      name: grpc
      appProtocol: grpc
    - port: 8180
      targetPort: 8180
      protocol: TCP
      name: grpc-8180
      appProtocol: grpc
