apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  namespace: sro-dev
  labels:
    app: accounts
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
      version: v1
  template:
    metadata:
      labels:
        app: accounts
        version: v1
    spec:
      containers:
        - name: accounts
          image: XXXXXXXXXX.dkr.ecr.XXXXXXXX.amazonaws.com/accounts:latest
          imagePullPolicy: Always
          env:
            - name: PS_AUTH_JWT_PRIVATE_KEY_PATH
              value: "/etc/sro/auth/keys/key"
            - name: PS_AUTH_JWT_PUBLIC_KEY_PATH
              value: "/etc/sro/auth/keys/key.pub"
            - name: SRO_AUTH_MODE
              value: "release"
          volumeMounts:
            - name: jwt-certs
              mountPath: "/etc/sro/auth/"
              readOnly: true
            - name: mysql-db
              mountPath: "/etc/sro/"
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: jwt-certs
          secret:
            secretName: sro-jwt.default
            items:
              - key: jwt.key
                path: key
              - key: jwt.key.pub
                path: key.pub
        - name: mysql-db
          secret:
            secretName: sro-db.default
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  namespace: sro-dev
  labels:
    app: accounts
    service: accounts
spec:
  type: ClusterIP
  selector:
    app: accounts
    version: v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http